.nh
.TH LIMA 1

.SH NAME
lima \- Lima: Linux virtual machines


.SH SYNOPSIS
\fBlima\fP [\fICOMMAND\fP\&...]


.SH DESCRIPTION
lima is an alias for "limactl shell default".
The instance name ("default") can be changed by specifying $LIMA_INSTANCE.

.PP
The shell and initial workdir inside the instance can be specified via $LIMA_SHELL
and $LIMA_WORKDIR.


.SH SEE ALSO
\fBlimactl\fP(1)
