name:  Instalaci贸n Autom谩tica Webmin + Virtualmin
description: Instalador universal con un solo comando para Ubuntu/Debian
title: "[BUG/FEATURE] "
labels: ["needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Gracias por reportar un issue. Por favor completa la informaci贸n solicitada.

  - type: dropdown
    id: tipo
    attributes:
      label: Tipo de Issue
      description: 驴Qu茅 tipo de issue est谩s reportando?
      options:
        - Bug/Error
        - Feature Request
        - Documentaci贸n
        - Pregunta/Soporte
    validations:
      required: true

  - type: dropdown
    id: sistema
    attributes:
      label: Sistema Operativo
      description: 驴En qu茅 sistema operativo ocurre el problema?
      options:
        - Ubuntu 20.04 LTS
        - Ubuntu 22.04 LTS
        - Ubuntu 18.04 LTS
        - Debian 10
        - Debian 11
        - Debian 12
        - Otro (especificar en descripci贸n)
    validations:
      required: true

  - type: textarea
    id: descripcion
    attributes:
      label: Descripci贸n del Problem/Feature
      description: Describe detalladamente el problema o feature solicitado
      placeholder: Describe tu problema o solicitud...
    validations:
      required: true

  - type: textarea
    id: pasos
    attributes:
      label: Pasos para Reproducir (solo para bugs)
      description: Lista los pasos para reproducir el problema
      placeholder: |
        1. Ejecut茅 el comando...
        2. El error apareci贸 cuando...
        3. Ver error...

  - type: textarea
    id: logs
    attributes:
      label: Logs/Output
      description: Pega aqu铆 los logs relevantes
      placeholder: |
        Pega aqu铆 el contenido de:
        /var/log/instalacion-webmin-virtualmin.log
      render: bash

  - type: textarea
    id: adicional
    attributes:
      label: Informaci贸n Adicional
      description: Cualquier otra informaci贸n relevante
      placeholder: Versiones, configuraciones especiales, etc...
