---
# Cost Reporting Tasks
# Implementa reportes automáticos de costos

- name: "Crear script de generación de reportes"
  template:
    src: "cost_reporting.py.j2"
    dest: "/opt/cost_monitoring/cost_reporting.py"
    owner: root
    group: root
    mode: '0755'

- name: "Crear directorio para reportes"
  file:
    path: "/var/lib/cost_monitoring/reports"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: "Configurar generación automática de reportes semanales"
  cron:
    name: "weekly_cost_report"
    minute: "0"
    hour: "8"
    weekday: "1"
    job: "/opt/cost_monitoring/cost_reporting.py weekly"
    user: root
    state: present

- name: "Configurar generación automática de reportes mensuales"
  cron:
    name: "monthly_cost_report"
    minute: "0"
    hour: "9"
    day: "1"
    job: "/opt/cost_monitoring/cost_reporting.py monthly"
    user: root
    state: present