---
# Webmin/Virtualmin RI Automation - FREE Implementation

- name: "Verificar que Webmin esté instalado"
  package:
    name: webmin
    state: present
  when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"

- name: "Verificar que Virtualmin esté instalado"
  stat:
    path: /usr/sbin/virtualmin
  register: virtualmin_installed
  ignore_errors: yes

- name: "Crear directorio para RI Automation en Webmin"
  file:
    path: "/etc/webmin/ri_automation"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: "Crear directorio para reportes de RI"
  file:
    path: "/etc/webmin/ri_reports"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: "Desplegar script de RI Automation gratuito"
  template:
    src: "webmin_ri_automation.py.j2"
    dest: "/usr/local/bin/webmin_ri_automation.py"
    owner: root
    group: root
    mode: '0755'

- name: "Crear script wrapper para Webmin"
  template:
    src: "webmin_ri_wrapper.sh.j2"
    dest: "/usr/local/bin/webmin-ri-automation"
    owner: root
    group: root
    mode: '0755'

- name: "Crear configuración inicial gratuita"
  template:
    src: "webmin_ri_config.json.j2"
    dest: "/etc/webmin/ri_automation_config.json"
    owner: root
    group: root
    mode: '0644'

- name: "Crear módulo Webmin para RI Automation"
  template:
    src: "webmin_ri_module.config.j2"
    dest: "/etc/webmin/ri_automation/module.config"
    owner: root
    group: root
    mode: '0644'

- name: "Crear página HTML para Webmin"
  template:
    src: "webmin_ri_dashboard.html.j2"
    dest: "/etc/webmin/ri_automation/index.html"
    owner: root
    group: root
    mode: '0644'

- name: "Crear script CGI para Webmin"
  template:
    src: "webmin_ri_cgi.cgi.j2"
    dest: "/etc/webmin/ri_automation/index.cgi"
    owner: root
    group: root
    mode: '0755'

- name: "Crear cron job para análisis automático gratuito"
  cron:
    name: "Webmin RI Automation - FREE"
    minute: "0"
    hour: "2"
    job: "/usr/local/bin/webmin-ri-automation --analyze"
    state: present

- name: "Ejecutar análisis inicial gratuito"
  command: "/usr/local/bin/webmin-ri-automation --analyze"
  register: ri_analysis_result
  changed_when: false
  ignore_errors: yes

- name: "Mostrar resultados del análisis inicial"
  debug:
    msg: "{{ ri_analysis_result.stdout_lines }}"
  when: ri_analysis_result.stdout_lines is defined

- name: "Crear enlace simbólico en Webmin"
  file:
    src: "/etc/webmin/ri_automation"
    dest: "/usr/libexec/webmin/ri_automation"
    state: link
  ignore_errors: yes

- name: "Reiniciar Webmin para cargar nuevo módulo"
  systemd:
    name: webmin
    state: restarted
    daemon_reload: yes
  ignore_errors: yes

- name: "Verificar funcionamiento del módulo RI"
  uri:
    url: "https://localhost:10000/ri_automation/"
    method: GET
    validate_certs: no
    status_code: 200
  register: webmin_check
  ignore_errors: yes

- name: "Mostrar estado de Webmin"
  debug:
    msg: "Webmin RI Automation module loaded successfully"
  when: webmin_check.status == 200

- name: "Crear documentación gratuita"
  template:
    src: "webmin_ri_readme.md.j2"
    dest: "/etc/webmin/ri_automation/README.md"
    owner: root
    group: root
    mode: '0644'