apiVersion: v1
kind: Secret
metadata:
  name: web-service-secrets
type: Opaque
stringData:
  app-secret-key: "replace-with-a-long-random-secret"
  jwt-secret-key: "replace-with-another-long-random-secret"
  jwt-salt: "replace-with-a-unique-jwt-salt"
  database-url: "postgresql://webmin_user:change_me@postgresql.webmin.svc.cluster.local:5432/webmin"
